use_tis: true
use_rs: true

tis_level: "token"
rs_level: "token"

tis_mode: "truncate"

tis_lower_bound: 0.5
tis_upper_bound: 2.0

rs_lower_bound: null
rs_upper_bound: null

rs_veto_threshold: 1.0e-4

tis_batch_normalize: true
